(* ::Package:: *)

(* ::Input:: *)
(*AppendTo[$Path,FileNameJoin[{"C:\\Users\\rende\\OneDrive\\Desktop\\baka\\mathematica"}]];*)
(**)
(*<<SurfacePattern`*)
(*sc = 10^-3;*)
(*{R1,R2,R3,R4,d,cw,edge}=sc{0.6,1,2.2,8,0.14,0.04,1};*)
(*{R1,R2,R3,R4}/(10^-3);*)
(**)
(*\[ScriptCapitalB]11 = ImplicitRegion[x^2+y^2 >= R1^2 && x^2+y^2 <= R2^2,{x,y}];*)
(*\[ScriptCapitalB]12 = ImplicitRegion[x^2+y^2 >= R3^2 && x^2+y^2 <= R4^2 && y >= cw && x >= cw,{x,y}];*)
(*\[ScriptCapitalB]22 = ImplicitRegion[x^2+y^2 >= R3^2 && x^2+y^2 <= R4^2 && y <= -cw && x >= cw,{x,y}];*)
(*\[ScriptCapitalB]32 = ImplicitRegion[x^2+y^2 >= R3^2 && x^2+y^2 <= R4^2 && y >= cw && x <= -cw, {x,y}];*)
(*\[ScriptCapitalB]42 = ImplicitRegion[x^2+y^2 >= R3^2 && x^2+y^2 <= R4^2 && y <= -cw && x <= -cw,{x,y}];*)
(*\[ScriptCapitalB]51 = ImplicitRegion[x-y>=-d/2 && x-y<=d/2 && x^2+y^2>=R2^2 &&x^2+y^2<=R3^2 && x<=0, {x,y}];*)
(*\[ScriptCapitalB]61 = ImplicitRegion[x-y>=-d/2 && x-y<=d/2 && x^2+y^2>=R2^2 &&x^2+y^2<=R3^2 && x>=0, {x,y}];*)
(*\[ScriptCapitalB]71 = ImplicitRegion[x+y>=-d/2 && x+y<=d/2  && x^2+y^2>=R2^2 &&x^2+y^2<=R3^2 && x<=0, {x,y}];*)
(*\[ScriptCapitalB]81 = ImplicitRegion[x+y>=-d/2 && x+y<=d/2  && x^2+y^2>=R2^2 &&x^2+y^2<=R3^2 && x>=0, {x,y}];*)
(*\[ScriptCapitalR]1 = RegionUnion[\[ScriptCapitalB]11,\[ScriptCapitalB]12,\[ScriptCapitalB]61];*)
(*\[ScriptCapitalR]2 = RegionUnion[\[ScriptCapitalB]22,\[ScriptCapitalB]81];*)
(*\[ScriptCapitalR]3 = RegionUnion[\[ScriptCapitalB]32,\[ScriptCapitalB]71];*)
(*\[ScriptCapitalR]4 = RegionUnion[\[ScriptCapitalB]42,\[ScriptCapitalB]51];*)
(*\[ScriptCapitalR] = RegionUnion[\[ScriptCapitalR]1,\[ScriptCapitalR]2,\[ScriptCapitalR]3,\[ScriptCapitalR]4];*)


(* ::Input:: *)
(*eleON=MeshPrimitives[DiscretizeRegion[\[ScriptCapitalR]],2]//.{Polygon[x_]->PolygonPixel[x]};*)
(*(*eleON2=MeshPrimitives[DiscretizeRegion[\[ScriptCapitalR]2],2]//.{Polygon[x_]->PolygonPixel[x]};*)*)
(*\[CapitalPhi][d_,{x_,y_,z_}]:=ComputeFinitePotential[d,eleON,{x,y,z}]*)
(*W[{x_,y_,z_}]:=# . #&[\[CapitalPhi][1,{x,y,z}]]*)
(*wc=Compile[{x,y,z},Evaluate[W[{x,y,z}]]];*)
(*Wc[{x_?NumericQ,y_?NumericQ,z_?NumericQ}]:=wc[x,y,z]*)
(**)
(*BeginPackage["targetFunctions`"];*)
(*FUN::usage="FUN[{s1,s2,s3}]";*)
(*Begin["Private`"];*)
(*FUN[{s1_,s2_,s3_}]:=Wc[{s1,s2,s3}];*)
(*Return[FUN];*)
(*End[];*)
(*EndPackage[];*)
